Traceback (most recent call last):
  File "/Users/danypineault/anaconda3/envs/IAM-Book/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/danypineault/anaconda3/envs/IAM-Book/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danypineault/anaconda3/envs/IAM-Book/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danypineault/anaconda3/envs/IAM-Book/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/danypineault/anaconda3/envs/IAM-Book/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/danypineault/anaconda3/envs/IAM-Book/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/danypineault/anaconda3/envs/IAM-Book/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = pl.subplots()
T = np.linspace(0, 4, 1000)
for a1 in [0.00236, 0.01, 0.1]:
    dice.a2 = a1
    ax.plot(
        T,
        dice.fDAMFRAC([T], 0),
        label=r"$a_1=" + str(a1) + "$" + ("(DICE2023)" if a1 == a1DICE else ""),
    )
    
ax.legend(frameon=False)
ax.set_xlabel("temperature change, $\Delta T$")
ax.set_ylabel("fraction productivity destroyed")
ax.set_ylim(0, 0.5)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 4[0m
[1;32m      2[0m T [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m, [38;5;241m4[39m, [38;5;241m1000[39m)
[1;32m      3[0m [38;5;28;01mfor[39;00m a1 [38;5;129;01min[39;00m [[38;5;241m0.00236[39m, [38;5;241m0.01[39m, [38;5;241m0.1[39m]:
[0;32m----> 4[0m     dice[38;5;241m.[39ma2 [38;5;241m=[39m a1
[1;32m      5[0m     ax[38;5;241m.[39mplot(
[1;32m      6[0m         T,
[1;32m      7[0m         dice[38;5;241m.[39mfDAMFRAC([T], [38;5;241m0[39m),
[1;32m      8[0m         label[38;5;241m=[39m[38;5;124mr[39m[38;5;124m"[39m[38;5;124m$a_1=[39m[38;5;124m"[39m [38;5;241m+[39m [38;5;28mstr[39m(a1) [38;5;241m+[39m [38;5;124m"[39m[38;5;124m$[39m[38;5;124m"[39m [38;5;241m+[39m ([38;5;124m"[39m[38;5;124m(DICE2023)[39m[38;5;124m"[39m [38;5;28;01mif[39;00m a1 [38;5;241m==[39m a1DICE [38;5;28;01melse[39;00m [38;5;124m"[39m[38;5;124m"[39m),
[1;32m      9[0m     )
[1;32m     11[0m ax[38;5;241m.[39mlegend(frameon[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

[0;31mNameError[0m: name 'dice' is not defined

